ARITHMETIC OPERATION

In [3]:
import numpy as np

a1=np.array([1,2,3,4,5])
a2=np.arange(6,11)
a1,a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [5]:
#a1 + a2 will directluy add all the elements index wiese together and it it is necessary
#that all the arrays contains same index
sum1=a1+a2#6+1,2+7,........
sum1

array([ 7,  9, 11, 13, 15])

In [7]:
diff=a1-a2
diff

array([-5, -5, -5, -5, -5])

In [8]:
multi=a1*a2
multi

array([ 6, 14, 24, 36, 50])

In [10]:
floardivision=a2//a1
floardivision

array([6, 3, 2, 2, 2])

BROADCASTING
---->It actually means that to do a single operation on all the elements together

In [12]:
l=[10,20,30,40]
arr=np.array(l)#list is converted into an array

In [14]:
arr+5

array([15, 25, 35, 45])

Deep And Shallow Copy

In [15]:
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
slice=a[0:5]
slice

array([1, 2, 3, 4, 5])

In [19]:
slice=slice*10
slice
#Yaha pei toh change hua but ye change apna main array mei koi change mhi krega 
#magar agar apnei paas ek list hoti toh original list mei bhii change ho jata 
"""THIS IS THE CONCEPT OF SHALLOW COPY"""
#a arary and slice array are at diff places in ram

array([10, 20, 30, 40, 50])

In [20]:
b=a
#change in b will effect change in a cause they both are in same place at ram 
b[0]=99
a
"""This is Deep copy 
to avoid this we can use b=a.copy() it will not affect a elements
"""



array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

MATRIX OPERATION


In [23]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [25]:
#multiplication

Matrix_multi=A@B
Matrix_multi

array([[19, 22],
       [43, 50]])

In [27]:
#or we can also use
multi=np.dot(A,B)
multi

array([[19, 22],
       [43, 50]])

In [28]:
#Transpose
A.T#Just write Matrix.T it will transpose the matrix 

array([[1, 3],
       [2, 4]])

Advance ArraY Manipulation

In [41]:
"""Stacking Array"""
#We can't stack two matrix 
# We can only stack two vectors or Two Arrays
nums1=np.array([1,2,3,4,5])
nums2=np.array([5,6,7,8,9])

In [42]:
#Vertical stack
np.vstack((nums1,nums2))

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [44]:
#Vertical Stack
np.hstack((nums1,nums2))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [45]:
#coloumn satck
np.column_stack((nums1,nums2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

SPLITING ARRAY

In [47]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.hsplit(c,4)
#it will split matrix horizontally in 4 parts 
#np.hsplit(matrix,parts)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [52]:
#Vertical split
np.vsplit(c,4)


[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]