In [2]:
#numpy is writeen in c ,which are compiled and superfast. This is the main reason Numpy is upto 50x faster than python list
#Numpy arrays
#how is it differrent from listt
#it can store only same data type, Much faster than list,More efficiency,Vector operations are easy+Fast

import numpy as np

In [7]:
#Basic array creation
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [1]:
a=[1,2,3,4,5,"hello"]
a

[1, 2, 3, 4, 5, 'hello']

In [5]:
import numpy as np

a = [1, 2, 3, 4, 5, "hello"]
np.array(a)
# all the values stay as Python objects when dtype=object is used

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [8]:
lst=[[1,2,3],[4,5,6],[7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr=np.arange(1,11,2)#just like range (star,stop,steps)
arr

array([1, 3, 5, 7, 9])

In [ ]:
#generating zeroes
#np.zeros((rows,coloumns))
arr=np.zeros((6,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#generate one
#np.ones
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#linspace evenly space de deteta hai 2 numbers ke beech mei jitna chahe utna ka 
#not like arange() ki jitna numbers tak hai wai tak dunga 

arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

RANDOM GENERATION FUNCTION

In [ ]:
#jab numpy install krtei hai tabhi isme import wala bhi aa jata hai

np.random.rand(10)#NORMALIZATION FROM 0 TO 1
#this will generate a vecto agar [] ye hai toh vector agar [[]] ye hai toh matrix

array([0.93149375, 0.21628919, 0.89671206, 0.53483023, 0.38696531,
       0.49070685, 0.77632515, 0.72973989, 0.7949786 , 0.45780794])

In [24]:
np.random.randn(10)#THIS IS STANDARDLIZATION FROM -3 TO 3

array([ 0.35093089, -0.88124469,  0.59345843,  0.38067846, -0.41772989,
       -2.04426395, -0.68152147, -0.32396747, -1.43583396, -0.62031259])

In [ ]:
np.random.randint(1,20,5)#kha se, kaha tak , or kitna number

array([18, 13, 13, 18,  6], dtype=int32)

ARRAY ATTRIBUTES

In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape#attribute kei () ye nhi likhte arr.shape() likhna wrong hai
#output will be 3,3 cause 3 rows and 3 colns

(3, 3)

In [ ]:
arr.size#no.of elements

9

In [ ]:
arr.dtype#tell our data type

dtype('int64')

ARRAY METHODS

In [33]:
arr.min()

np.int64(1)

In [34]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [37]:
np.sum(arr,axis=0)#axis = 0 then we are axising coloumnif axis = 1 we are acessing rows


array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)#it will tell row sum

array([ 6, 15, 24])

In [ ]:
np.max(arr,axis=1)#max element in each rows

array([3, 6, 9])

In [40]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()#standard deviatation 

np.float64(2.581988897471611)

In [ ]:
arr.argmax()#index of max element

np.int64(8)

In [43]:
arr.argmin()#index of minimum element

np.int64(0)

RESHAPING AND RESIZING


In [ ]:
arr=np.arange(1,31)
arr#this is a vector now we will convert it into matrix using reshaping 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

NUMPY INDEXING

In [47]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr[0]

np.int64(11)

In [50]:
#slicing
arr[0:5:1]

array([11, 12, 13, 14, 15])

NUMPY INDEXING AND SLICING of MATRIX

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr
#6 rows and 5 coloumns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#arr[rows][coloumns]
arr[0]#it will 1st row

array([1, 2, 3, 4, 5])

In [55]:
arr[0][1]

np.int64(2)

In [ ]:
#SLICING 2,3
#        7,8
#arr[row mei start:stop,coloumn mei start:stop]
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [59]:
slice=arr[3::,3::]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [62]:
#slicing a whole coloumn
slice=arr[::,1]
slice

array([ 2,  7, 12, 17, 22, 27])

BOOLEAN INDEXING

In [67]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
#we want only  even numbers
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [68]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])