Valid Suduko

In [81]:
import numpy as np

In [82]:
#In suduko there are 9 3by3 blocks
#Every rows and coloumns should give a sum of 45i.e 1+.....+9
#Every block should also have a sum of 45
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [83]:
#sum of each and every row
b=np.sum(s,axis=1)
#checking
b==45
#or 
for i in b:
    if i!=45:
        break 
else:
    print("for rows it is valid")


for rows it is valid


In [84]:
#sum of each coloumn
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        break
else:
    print("For coloumns it is valid")



For coloumns it is valid


In [85]:
#checking block sum
# a=s[0:3,0:3]
# a
# if a.sum()!=45:
#     print("MAke some changes in this block")
# else:
#     print("Valid Block")

In [86]:
#Logic for sum of each block
for i in range(0,9,3):#to acess rows in s 
    for j in range(0,9,3):#to acess coloumns in s
        n=s[i:i+3,j:j+3]#it will do s[0:3,0:3]for i=0 
        print(n.sum())
    

45
45
45
45
45
45
45
45
45


GENERAL QUESTION

In [87]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [88]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [89]:
#Find the average age of students.
age=data[::,:1:]
age.mean()

np.float64(18.4)

In [90]:
#Extract Math marks of all students.
math_marks=data[::,1:2]
print(f"The marks of math is :\n{math_marks}")

The marks of math is :
[[85]
 [92]
 [76]
 [65]
 [90]]


In [91]:
#Find the highest Science mark.
max_science=data[::,2::]
print(f"highest Science mark: {max_science.max()}")

highest Science mark: 95


In [92]:
#Get details of the student who scored more than 90 in Math.
details=data[data[::,1]>90]
details

array([[19, 92, 88]])

In [93]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [94]:
#Find how many students are younger than 19.
younger=data[data[:,0]<19]
len(younger)


3

In [95]:
#Calculate the average marks in each subject (column-wise mean).
coloumnmean=data[:,1:]
np.mean(coloumnmean,axis=0)

array([86.6, 83.2])

In [96]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]
#use this when there is a condition that we have to apply to filter our data

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [98]:
#Replace all Science marks <75 with 0
# acessing coloumn and then performing opertaion on that coloumn
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])